In [1]:
import numpy as np

In [9]:
train_X = np.random.randint(1,6, size = (10, 4))
test = np.random.randint(1,6, size = (5, 4))
test_first = test[0]

In [100]:
def compute_distances_two_loops(X):
    num_train = train_X.shape[0]
    num_test = X.shape[0]
    dists = np.zeros((num_test, num_train), np.float32)
    for i_test in range(num_test):
        for i_train in range(num_train):
            train_vector = train_X[i_train]
            test_vector = X[i_test]

            distance = np.sum(np.abs(train_vector - test_vector), axis = 0)

            dists[i_test, i_train] = distance

    return dists


def compute_distances_one_loop(X):
    
    num_train = train_X.shape[0]
    num_test = X.shape[0]
    dists = np.zeros((num_test, num_train), np.float32)
    for i_test in range(num_test):
        
        distances = train_X - X[i_test]
        
        norms = np.sum(np.abs(distances), axis=1)
        dists[i_test] = norms
    return dists


def compute_distances_no_loops(X):
    num_train = train_X.shape[0]
    num_test = X.shape[0]
    # Using float32 to to save memory - the default is float64
    dists = np.zeros((num_test, num_train), np.float32)
    
    test_tensor = X[:, np.newaxis, :]
    
    train_tensor = train_X[np.newaxis, :, :]
    
    distances = train_tensor - test_tensor
    
    norms = np.sum(np.abs(distances), axis=2)

    dists = norms
    
    return dists


In [101]:
two_loops_result = compute_distances_two_loops(test)

two_loops_result

array([[ 8.,  6.,  8., 10.,  6.,  6.,  6.,  9.,  5.,  4.],
       [ 7.,  5.,  5.,  9.,  7.,  3.,  5.,  8.,  4.,  5.],
       [ 9.,  7.,  5.,  5.,  5.,  5.,  5.,  4., 10.,  7.],
       [ 9.,  9.,  5.,  5.,  3.,  3.,  3.,  4.,  8.,  7.],
       [ 4.,  8.,  0.,  6.,  6.,  2.,  4.,  7.,  7.,  8.]], dtype=float32)

In [102]:
one_loop_result = compute_distances_one_loop(test)

one_loop_result

array([[ 8.,  6.,  8., 10.,  6.,  6.,  6.,  9.,  5.,  4.],
       [ 7.,  5.,  5.,  9.,  7.,  3.,  5.,  8.,  4.,  5.],
       [ 9.,  7.,  5.,  5.,  5.,  5.,  5.,  4., 10.,  7.],
       [ 9.,  9.,  5.,  5.,  3.,  3.,  3.,  4.,  8.,  7.],
       [ 4.,  8.,  0.,  6.,  6.,  2.,  4.,  7.,  7.,  8.]], dtype=float32)

In [103]:
no_loops_result = compute_distances_no_loops(test)

no_loops_result

array([[ 8,  6,  8, 10,  6,  6,  6,  9,  5,  4],
       [ 7,  5,  5,  9,  7,  3,  5,  8,  4,  5],
       [ 9,  7,  5,  5,  5,  5,  5,  4, 10,  7],
       [ 9,  9,  5,  5,  3,  3,  3,  4,  8,  7],
       [ 4,  8,  0,  6,  6,  2,  4,  7,  7,  8]])

In [36]:
train_X

array([[1, 3, 5, 1],
       [1, 5, 4, 4],
       [2, 2, 3, 1],
       [1, 1, 5, 3],
       [5, 2, 2, 3],
       [3, 2, 3, 2],
       [3, 1, 4, 2],
       [4, 1, 3, 5],
       [4, 5, 1, 1],
       [5, 4, 3, 4]])

In [37]:
test

array([[5, 5, 4, 2],
       [3, 5, 3, 2],
       [2, 1, 2, 4],
       [3, 1, 2, 3],
       [2, 2, 3, 1]])

In [62]:
test[:,np.newaxis, :]

array([[[5, 5, 4, 2]],

       [[3, 5, 3, 2]],

       [[2, 1, 2, 4]],

       [[3, 1, 2, 3]],

       [[2, 2, 3, 1]]])

In [79]:
distances = train_X[np.newaxis, :, :] - test[:,np.newaxis, :]

In [80]:
distances.shape

(5, 10, 4)

In [81]:
distances

array([[[-4, -2,  1, -1],
        [-4,  0,  0,  2],
        [-3, -3, -1, -1],
        [-4, -4,  1,  1],
        [ 0, -3, -2,  1],
        [-2, -3, -1,  0],
        [-2, -4,  0,  0],
        [-1, -4, -1,  3],
        [-1,  0, -3, -1],
        [ 0, -1, -1,  2]],

       [[-2, -2,  2, -1],
        [-2,  0,  1,  2],
        [-1, -3,  0, -1],
        [-2, -4,  2,  1],
        [ 2, -3, -1,  1],
        [ 0, -3,  0,  0],
        [ 0, -4,  1,  0],
        [ 1, -4,  0,  3],
        [ 1,  0, -2, -1],
        [ 2, -1,  0,  2]],

       [[-1,  2,  3, -3],
        [-1,  4,  2,  0],
        [ 0,  1,  1, -3],
        [-1,  0,  3, -1],
        [ 3,  1,  0, -1],
        [ 1,  1,  1, -2],
        [ 1,  0,  2, -2],
        [ 2,  0,  1,  1],
        [ 2,  4, -1, -3],
        [ 3,  3,  1,  0]],

       [[-2,  2,  3, -2],
        [-2,  4,  2,  1],
        [-1,  1,  1, -2],
        [-2,  0,  3,  0],
        [ 2,  1,  0,  0],
        [ 0,  1,  1, -1],
        [ 0,  0,  2, -1],
        [ 1,  0,  1,  2],
      

In [82]:
res = np.sum(np.abs(distances), axis=2)
distances = train_X[np.newaxis, :, :] - test[:,np.newaxis, :]
res

array([[ 8,  6,  8, 10,  6,  6,  6,  9,  5,  4],
       [ 7,  5,  5,  9,  7,  3,  5,  8,  4,  5],
       [ 9,  7,  5,  5,  5,  5,  5,  4, 10,  7],
       [ 9,  9,  5,  5,  3,  3,  3,  4,  8,  7],
       [ 4,  8,  0,  6,  6,  2,  4,  7,  7,  8]])

In [1]:
def good_students(colegium):
    avg_grade = sum(student[2] for student in colegium) / len(colegium)
    good_students_list = [student[0] for student in colegium if student[2] > avg_grade]
    print(f"Студенти {', '.join(good_students_list)} у поточному семестрі навчалися добре.")

colegium = (
    ("Ivanov", 20, 60),
    ("Kori", 18, 73),
    ("Gonchar", 19, 76),
    ("Afonov", 20, 67),
    ("Kornilov", 18, 85),
    ("Besarab", 18, 88),
    ("Frolov", 19, 90),
)

good_students(colegium)

Студенти Kornilov, Besarab, Frolov у поточному семестрі навчалися добре.


In [3]:
import numpy as np

In [4]:
def good_students(colegium):
    colegium_array = np.array(colegium, dtype=object)
    print(f"Студенти {', '.join(colegium_array[colegium_array[:, 2].astype(float) > np.mean(colegium_array[:, 2].astype(float)), 0])} у поточному семестрі навчалися добре.")

good_students(colegium)


Студенти Kornilov, Besarab, Frolov у поточному семестрі навчалися добре.
